name: physio_tracker_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_range_picker: ^1.0.5
  geoflutterfire: ^2.0.3+5
  flutter_google_places: ^0.2.3
  cloud_functions: ^0.4.1+2
  cloud_firestore: ^0.13.0+1
  firebase_messaging: ^6.0.9
  firebase_core: ^0.4.0
  firebase_auth: ^0.15.3
  flutter_facebook_login: ^3.0.0
  firebase_storage: ^3.0.2
  google_sign_in: ^4.0.14
  image_picker: ^0.6.0+10
  font_awesome_flutter: ^8.5.0
  flutter_svg: ^0.15.0
  geolocator: 5.1.3
  provider: ^3.0.0+1
  url_launcher: ^5.1.1
  month_picker_dialog: ^0.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dots_indicator: ^0.0.5+1
  shared_preferences: ^0.5.2
  auto_size_text: ^2.0.2
  intl: ^0.16.0
  flutter_launcher_icons: "^0.7.2"
  flutter_datetime_picker: 1.2.8
  datetime_picker_formfield: ^1.0.0
  grouped_buttons: ^1.0.4
  flutter_calendar_carousel: ^1.3.18
  cached_network_image: ^2.0.0
  multi_image_picker: ^4.6.1
  carousel_pro: ^1.0.0
  overlay_support: ^1.0.2
  bubble: ^1.1.9+1
  flutter_image_compress: ^0.6.3
  permission_handler: ^4.0.0
  contacts_service: ^0.3.10
  flutter_sms: ^1.1.0
  flutter_blue: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/splashScreen/android_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Avenir-Reg
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
    - family: Avenir-Lig
      fonts:
        - asset: assets/fonts/AvenirLTStd-Light.otf
    - family: Avenir-Med
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.ttf
    - family: Montserrat-Reg
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Med
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Lig
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf


  assets:
    - assets/images/kiqback_logo.png
    - assets/images/login_background.jpg
    - assets/images/default_profile_image.png
    - assets/images/default_cover_photo.jpg
    - assets/images/entertainment.jpeg
    - assets/images/nightlife.jpeg
    - assets/images/technology.jpeg
    - assets/images/professional.jpeg
    - assets/images/fitness.jpeg
    - assets/images/beauty.jpeg
    - assets/images/default.jpg
    - assets/images/squats.png
    - assets/images/hip_adduction.png
    - assets/images/knee_flexion_extension.jpg
    - assets/illustrations/onboardingScreen1.svg
    - assets/illustrations/onboardingScreen2.svg
    - assets/illustrations/onboardingScreen3.svg
    - assets/illustrations/notLoggedInScreen.svg
    - assets/illustrations/noEventScreen.svg
    - assets/illustrations/noMessageScreen.svg
    - assets/illustrations/noNotificationScreen.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
